name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install pylint
        run: pip install pylint==3.3.7
      - name: Run pylint
        run: |
          pylint --exit-zero core tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -q
